name: Deploy to Azure Container Apps

on:
  workflow_dispatch:
  push:
    branches:
      - deploy

env:
  AZURE_RESOURCE_GROUP: gh-demo
  AZURE_CONTAINER_REGISTRY: acrghdemorlacf

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Build the application
        run: dotnet build SampleApp/SampleApp.sln --configuration Release 

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get ACR access token
        id: acr_token
        run: |
            ACR_TOKEN=$(az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }} --expose-token --output tsv --query accessToken)
            echo "token=${ACR_TOKEN}" >> $GITHUB_OUTPUT

      - name: Log in to Docker with new token
        uses: docker/login-action@v3
        with:
            registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
            username: 00000000-0000-0000-0000-000000000000
            password: ${{ steps.acr_token.outputs.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Build and push Docker image to ACR - BackEnd
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/backend:latest, ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/backend:${{ github.sha }}
          file: SampleApp/BackEnd/Dockerfile.original

      - name: Build and push Docker image to ACR - FrontEnd
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/frontend:latest, ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/frontend:${{ github.sha }}
          file: SampleApp/FrontEnd/Dockerfile.original


      - name: Deploy to Azure Container Apps - BackEnd
        uses: azure/container-apps-deploy-action@v1
        with:
            resourceGroup: ${{ env.AZURE_RESOURCE_GROUP }}
            containerAppName: backend
            imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/backend:latest

      - name: Deploy to Azure Container Apps - FrontEnd
        uses: azure/container-apps-deploy-action@v1
        with:
            resourceGroup: ${{ env.AZURE_RESOURCE_GROUP }}
            containerAppName: frontend
            imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/frontend:latest
